title: 'xDCI Cross-disciplinary Data CyberInfrastructure'
default_lang: en
author:
  name: 'Kelsey Urgo'
  email: kelseyurgo@renci.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Cross-disciplinary Data CyberInfrastructure xDCI'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
